### ISSUE TITLE
Display list of evangelists

### ISSUE THREAD

**Issue by dolftax** [MozillaIndia/vibe#11]
Follow the discussion here - MozillaIndia/old-vibe/issues/25

Example JSON

```
{
     "name" : "Manish Goregaokar",
     "github" : "http://github.com/Manishearth",
     "topics" : ["Firefox","Rust","Servo","Javascript"],
     "developer" : true,  
     "location" : "Mumbai",
     "mozillians" : "https://mozillians.org/en-US/u/manishearth"
}
```

**Comment by akhilpandey95** [comment]
Working on it !!

**Comment by abhi12ravi** [comment]
@AkhilHector How's this coming up?

**Comment by akhilpandey95** [comment]
Pretty fine man im almost done . Just submitting a pr is left expect it today !!

**Comment by abhi12ravi** [comment]
(y)

**Comment by abhi12ravi** [comment]
:thumbsup:

**Comment by siddhartharao17** [comment]
Is this issue fixed? I wish to work on it..

**Comment by dolftax** [comment]
@AkhilHector is working on it, as per his comment. I would recommend you to take some other issue and work on it.

**Comment by dolftax** [comment]
@AkhilHector Status of this issue?

**Comment by akhilpandey95** [comment]
Im almost done, Sorry for the delay will submit the PR today.

**Comment by dolftax** [comment]
The view and controller for evangelists listing is pushed - https://github.com/MozillaIndia/vibe/commit/06d842fe47c6557a8501429cc3666723511f50f8

CSS needs to be fixed.

Note : Send PRs to `evangelists` branch.

**Comment by kaustavdm** [comment]
@dolftax Quick question: Can we use the [Mozillians API v2](https://mozillians.readthedocs.org/en/latest/api/apiv2/index.html) and fetch the information from the [MozSpeakers](https://mozillians.org/en-US/group/mozspeakers/) group? Essentially, any member of the group with the `country` set to `India` should be shown in this list.

**Comment by kaustavdm** [comment]
This is what you need:

`GET https://mozillians.org/api/v2/users/?group=mozspeakers&api-key=yourkeyhere`

**Comment by dolftax** [comment]
The API is heavily broken and passing multiple parameters (group=mozspeakers&country=india) doesn't seem to give expected result.

@kaustavdm Is there any other workaround here you could think of?

**Comment by akhilpandey95** [comment]
Hey @kaustavdm instead of using gravatar what if we could use the github api and take the avatar from the github nick ?

**Comment by dolftax** [comment]
PR #18 fixed this for now. Let us wait for the stable release of mozillians API and implement it by then.

@AkhilHector :+1: Thanks!
