### ISSUE TITLE
Search box dislocates on larger screen sizes and retina displays.

### ISSUE THREAD

**Issue by sudheesh001** [MozillaIndia/vibe#13]
![screen shot 2015-06-27 at 12 22 50 pm](https://cloud.githubusercontent.com/assets/4545925/8390872/530a924a-1cc7-11e5-990a-c500ca7cfcdd.png)

This should rather be center aligned along with the cards on all screen resolutions. Looks like an easy fix.

**Comment by sudheesh001** [comment]
Fixed.
![screen shot 2015-06-27 at 12 22 56 pm](https://cloud.githubusercontent.com/assets/4545925/8390895/2e71111a-1cc8-11e5-932c-c4e525630b3a.png)

**Comment by akhilpandey95** [comment]
Hey jai can you replicate the bug because i was not getting the same error !!

**Comment by dolftax** [comment]
@AkhilHector As per the screenshot, the occurrence was confirmed on larger screen.
.. and is fixed now.
