### ISSUE TITLE
Fix the routing

### ISSUE THREAD

**Issue by dolftax** [MozillaIndia/vibe#19]
Go to `hostname/events` and hit reload. It returns 404.

Tip: `ui-router` module needs extra configuration to handle these breakages.

> Note: Send PR to evangelists branch.

**Comment by dolftax** [comment]
@AkhilHector want to take this?

**Comment by akhilpandey95** [comment]
@dolftax working on it

**Comment by dolftax** [comment]
@AkhilHector any update on this?

**Comment by akhilpandey95** [comment]
@dolftax yes please give me a day or so, i issue is resolved, will send the PR soon !

**Comment by akhilpandey95** [comment]
I know this is sort of a hack but if we comment L6 in controllers/router.js, The page reload works absolutely fine. What say @dolftax 
![ques](https://cloud.githubusercontent.com/assets/5903056/9293079/2f9d07da-443a-11e5-9052-0d03c5dd8b97.png)

**Comment by asdofindia** [comment]
Do you think you need a server?

**Comment by akhilpandey95** [comment]
@asdofindia I am sorry i din't get you !

**Comment by asdofindia** [comment]
@AkhilHector How's hostname/events gonna reach the route specified in index.html unless the server itself routes it to the index.html? I suggest we use express and host it on the mozilla india vps [More info](https://fdietz.github.io/recipes-with-angular-js/urls-routing-and-partials/using-regular-urls-with-the-html5-history-api.html)

**Comment by asdofindia** [comment]
Or, resort to html4 itself like you suggested. Why run an express instance just for this.

**Comment by akhilpandey95** [comment]
Yes actually we should configure the router such that we donot have a page reload problem, that is the issue about and there is absolutely no need for the usage of an express server. And apart from that since we using $locationProvider.html5Mode(true) then hostname/events or hostname/evangelists must inject the state even on on window reload and refresh which won't happen in this case.

**Comment by asdofindia** [comment]
I challenge you to do that without a server side redirect.

**Comment by akhilpandey95** [comment]
hahah @asdofindia  the issue is already solved

**Comment by asdofindia** [comment]
Cool then! :dart:

**Comment by dolftax** [comment]
@asdofindia @AkhilHector , When hashbang ( /#/foo , default mode ) is used along with UI router, page reload works as expected. But to get rid of hashes, we use html5 mode, which when used with UI router, needs server configuration. We can't do it in github's server.

I used UI router because 1) it can handle deeply nested multiple views, 2) it is almost all angular dev's default choice.  But I guess, we can switch back to angular's default router, as we don't have multiple nested views. Also, in such case, we can host it in github itself 1) without hashes in urls 2) with refresh working perfectly.

What do you say?

**Comment by akhilpandey95** [comment]
@dolftax  Yes we could switch back but there are many perks of using ui router like, linking states based on state names and if we change a url in one place it will update every link connected to the state, so let us give it a thought for and personally i feel we can stay with using ui router over to ngroute !!

**Comment by dolftax** [comment]
Reasons why we should switch back
- We don't want to run this app on a separate server, let it be on github pages
- We are not handling multiple nested views, we just got two views

**Comment by asdofindia** [comment]
@dolftax I don't see how switching to ngroute solves this issue any better than switching to html4mode does.

**Comment by dolftax** [comment]
@asdofindia, Please send a working PR for the same.

**Comment by dolftax** [comment]
@asdofindia In UI router, when you have html5Mode enabled, the # character will no longer be used in your urls. The # symbol is useful because it requires no server side configuration. Without #, the url looks much nicer, but it also requires server side rewrites. 

Which means, we have to configure the server. We don't want to / can't do that as we are hosting the app on gh-pages.

So, in our case, as we aren't hosting the app on our own server where we can rewrite as we want, there is no way to 
- avoid hashes in URL 
- use UI router module and
- get page refresh work as expected

Ref - https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

Hope that helps!

**Comment by asdofindia** [comment]
@dolftax, that's exactly why not switching to html5mode is the solution.

**Comment by dolftax** [comment]
Ah. You misunderstood the point. I was talking about switching to ngRoute.

**Comment by asdofindia** [comment]
Well, why switch the entire thing when you can achieve whatever is required by deleting a line?

**Comment by dolftax** [comment]
meh! You don't seem to understand. Let us move this discussion to #india ?

**Comment by dolftax** [comment]
Hashbang it is!
