### ISSUE TITLE
Fix the stylesheets

### ISSUE THREAD

**Issue by dolftax** [MozillaIndia/vibe#4]
The UI should look like - https://github.com/MozillaIndia/old-vibe

Reuse from the below links (needs cleanup). No redundancy.
- https://github.com/MozillaIndia/old-vibe/blob/master/assets/css/events.css
- https://github.com/MozillaIndia/old-vibe/blob/master/assets/css/global.css
- https://github.com/MozillaIndia/old-vibe/blob/master/assets/css/site.css

**Comment by akhilpandey95** [comment]
Fixed !!
